### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by fleoparra** [L4Digital/FastScroll#34]
Hi.

We use fast scroller on a recycler view but some of user's session (We use Fabric) show this error:

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.support.v7.widget.RecyclerView.computeVerticalScrollOffset()' on a null object reference
       at com.l4digital.fastscroll.FastScroller.getScrollProportion(FastScroller.java:443)
       at com.l4digital.fastscroll.FastScroller.access$000(FastScroller.java:51)
       at com.l4digital.fastscroll.FastScroller$3.run(FastScroller.java:221)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:251)
       at android.app.ActivityThread.main(ActivityThread.java:6589)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

Library Version:
api 'com.l4digital.fastscroll:fastscroll:1.1.1'

**Comment by randr0id** [comment]
This was fixed by pull request #32. I will be releasing an update that includes this fix soon, and will then update this issue.

**Comment by randr0id** [comment]
Fixed with commit 6602d1c and released in version 1.1.2.

**Comment by zacharyyy** [comment]
@randr0id I was just about to post this issue! Thanks for the fix and the awesome lib :)

**Comment by randr0id** [comment]
Hi @zacharyyy! Thanks for the support :grin:
